starting(a).
starting(b).
starting(c).
starting(d).
starting(e).
starting(f).
starting(g).
starting(h).
starting(i).
starting(j).
starting(k).
starting(l).
starting(m).
starting(n).
starting(o).
starting(p).
starting(q).
starting(r).
starting(s).
starting(x).
edge(a,b,blue).
edge(a,d,blue).
edge(a,f,blue).
edge(b,c,blue).
edge(b,h,blue).
edge(c,j,blue).
edge(c,e,blue).
edge(e,l,blue).
edge(e,d,blue).
edge(d,n,blue).
edge(f,k,blue). 
edge(f,m,blue).
edge(m,r,blue).
edge(m,n,blue).
edge(n,x,blue).
edge(x,s,blue).
edge(x,f,blue).
edge(f,g,blue).
edge(g,o,blue).
edge(g,h,blue).
edge(h,i,blue).
edge(i,j,blue).
edge(i,p,blue).
edge(j,k,blue).
edge(k,l,blue).
edge(k,q,blue).
edge(l,m,blue).
edge(o,p,blue).
edge(p,q,blue).
edge(q,r,blue).
edge(r,s,blue).
edge(s,o,blue).


node(X, red) | node(X, yellow) | node(X, green) :- starting(X).
:- node(X,C),node(Y,C), edge(X,Y,_),X!=Y.